// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/12f9b621f914fe2b9486a74e0f2e130621837bfc/node-uuid/node-uuid-cjs.d.ts
declare module "node-uuid" {
    var uuid: __NodeUUID.UUID;
    export = uuid;
}
